spring:
  datasource:
    url: jdbc:mysql://sql:3306/your_database
    username: your_user
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  level:
    ROOT: info

management:
  endpoints:
    web:
      exposure:
        include: health, logfile, metrics
  endpoint:
    health:
      show-details: when_authorized
      roles: ADMIN

logging:
  file:
    name: log/book_storage_log.log
